title: Sahridhaya - Be Together Grow Together
mail: info@sahridhaya.org
phno: +91-9188183100
address: Palayam, Thiruvananthapuram, Kerala 695035
map: https://goo.gl/maps/SyGdC6t4CUaDgJ9g6
insta: https://www.instagram.com/sahridhaya/
fb: https://www.facebook.com/Sahridhaya/
years: 7
volunteers: 177
events: 69
assoc: 28
collections:
  causes:
    output: true
    permalink: :name.html
  partners:
    output: false
include:
  - images