title: Sahridhaya - Be Together Grow Together
mail: info@sahridhaya.org
phno: +91-8547978688
address: Palayam, Thiruvananthapuram, Kerala 695035
map: https://goo.gl/maps/SyGdC6t4CUaDgJ9g6
insta: https://www.instagram.com/sahridhaya/
fb: https://www.facebook.com/Sahridhaya/
collections:
  causes:
    output: true
    permalink: :name.html
include:
  - images